#! /usr/bin/env python

"""Convert a JSON association list to an object.
"""

import sys
import argparse
import json

def main(options):
    """Main program."""
    alist = json.load(sys.stdin)
    json.dump(dict(alist), sys.stdout, indent=4)
    return

def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
        description="Convert JSON alist to an object",
    )
    # parser.add_argument() calls here
    options = parser.parse_args()
    # extra processing of options here
    return options

if __name__ == "__main__":
    main(get_options())
